# log_level:
# none: 0 or else     log none
# error:1      log 1
# warning:2    log 1,2
# info:3       log 1,2,3
# debug:4      log 1,2,3,4
log:
  log_level: 3
td_ftp:
  server: '15.83.248.197'
  td_path: '/Files/scripts_data/wes'
  username: 'Administrator'
  password: 'Shanghai2020'
proxy:
  '15.85.199.199:8080'
alm_ftp:
  server: '15.83.248.197'
  username: 'Administrator'
  password: 'Shanghai2020'
  local_ftp_path: 'c:\ftp\scripts_report'  # alm server ftp local path
  report_path: 'scripts_report'  # alm ftp report path
